version: '3'
services:
    nginx:
        image: lnoering/nginx:latest
        ports:
            - "80:80"
            - "443:443"
        networks: ['tasks']
        tty: true
        volumes:
            - ./project/www/${PROJNAME}:/wwwroot/ecommerce/base/production/current
            - ./data/config/nginx/vhost:/etc/nginx/vhost/
        links:
            - php
        depends_on:
            - php

    php:
        image: lnoering/php:latest
        networks: ['tasks']
        tty: true
        volumes:
            - ./project/www/${PROJNAME}:/wwwroot/ecommerce/base/production/current

    database:
        image: mysql:5.7
        ports:
            - "3306:3306"
        networks: ['tasks']
        volumes:
            - ./data/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./project/database:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}    
volumes:
    esdata:
        driver: local

networks: {tasks: {}}